### ISSUE TITLE
text-2.0 support

### ISSUE THREAD

**Issue by tchoutri** [sjshuck/hs-pcre2#24] opened 2022-04-14 21:27 UTC
Hi, I'm trying to upgrade my application to use `text-2.0` but I'm encountering the following build failures:

```
Configuring library for pcre2-2.1.0.1..
Preprocessing library for pcre2-2.1.0.1..
Building library for pcre2-2.1.0.1..
[1 of 7] Compiling Paths_pcre2      ( dist/build/autogen/Paths_pcre2.hs, dist/build/Paths_pcre2.o, dist/build/Paths_pcre2.dyn_o )
[2 of 7] Compiling Text.Regex.Pcre2.Foreign.TH ( src/hs/Text/Regex/Pcre2/Foreign/TH.hs, dist/build/Text/Regex/Pcre2/Foreign/TH.o, dist/build/Text/Regex/Pcre2/Foreign/TH.dyn_o )
[3 of 7] Compiling Text.Regex.Pcre2.Foreign ( src/hs/Text/Regex/Pcre2/Foreign.hs, dist/build/Text/Regex/Pcre2/Foreign.o, dist/build/Text/Regex/Pcre2/Foreign.dyn_o )
[4 of 7] Compiling Text.Regex.Pcre2.Internal ( src/hs/Text/Regex/Pcre2/Internal.hs, dist/build/Text/Regex/Pcre2/Internal.o, dist/build/Text/Regex/Pcre2/Internal.dyn_o )

src/hs/Text/Regex/Pcre2/Internal.hs:89:21: error:
    Not in scope: type constructor or class ‘Text.I16’
    Perhaps you meant ‘Text.I8’ (imported from Data.Text.Foreign)
    Neither ‘Data.Text’ nor ‘Data.Text.Foreign’ exports ‘I16’.
   |
89 |     {-# UNPACK #-} !Text.I16
   |                     ^^^^^^^^

src/hs/Text/Regex/Pcre2/Internal.hs:90:21: error:
    Not in scope: type constructor or class ‘Text.I16’
    Perhaps you meant ‘Text.I8’ (imported from Data.Text.Foreign)
    Neither ‘Data.Text’ nor ‘Data.Text.Foreign’ exports ‘I16’.
   |
90 |     {-# UNPACK #-} !Text.I16
   |                     ^^^^^^^^

src/hs/Text/Regex/Pcre2/Internal.hs:102:11: error:
    Not in scope: ‘Text.takeWord16’
    Perhaps you meant ‘Text.takeWord8’ (imported from Data.Text.Foreign)
    Neither ‘Data.Text’ nor ‘Data.Text.Foreign’ exports ‘takeWord16’.
    |
102 |         & Text.takeWord16 offEnd
    |           ^^^^^^^^^^^^^^^

src/hs/Text/Regex/Pcre2/Internal.hs:103:11: error:
    Not in scope: ‘Text.dropWord16’
    Perhaps you meant ‘Text.dropWord8’ (imported from Data.Text.Foreign)
    Neither ‘Data.Text’ nor ‘Data.Text.Foreign’ exports ‘dropWord16’.
    |
103 |         & Text.dropWord16 off
    |           ^^^^^^^^^^^^^^^

src/hs/Text/Regex/Pcre2/Internal.hs:1063:31: error:
    Not in scope: type constructor or class ‘Text.I16’
    Perhaps you meant ‘Text.I8’ (imported from Data.Text.Foreign)
    Neither ‘Data.Text’ nor ‘Data.Text.Foreign’ exports ‘I16’.
     |
1063 |     let peekOvec :: Int -> IO Text.I16
     |                               ^^^^^^^^
```

**Comment by sjshuck** [comment] 2022-04-15 03:26
Duplicate of #22.

**Closed as completed by sjshuck** 2022-04-15 03:26 UTC
